# Generated by Django 3.1.12 on 2022-01-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('shipping', 'Shipping'), ('out for delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('returning', 'Returning')], default='available', max_length=20),
        ),
    ]
