# Generated by Django 3.1.12 on 2022-01-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220111_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='label',
            field=models.ImageField(blank=True, default=None, upload_to='static/images/dropcodes'),
        ),
    ]
