# Generated by Django 3.1.12 on 2021-12-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sport',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
