# Generated by Django 3.1.12 on 2021-12-08 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211208_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sport',
        ),
    ]
