# Generated by Django 3.1.12 on 2022-02-01 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220112_2025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drop',
            new_name='Section',
        ),
    ]
