# Generated by Django 3.1.12 on 2021-12-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sport',
            field=models.CharField(default=None, max_length=120, unique=True),
        ),
    ]
