# Generated by Django 3.1.12 on 2021-12-01 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20211201_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.variant'),
        ),
    ]
