# Generated by Django 3.1.12 on 2022-02-02 04:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0007_remove_order_supplier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buyer',
            new_name='Recipient',
        ),
    ]
