# Generated by Django 3.1.12 on 2022-02-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20220201_2053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Office',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='office',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='office',
            new_name='location',
        ),
    ]
