# Generated by Django 3.1.12 on 2021-12-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20211209_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
