# Generated by Django 3.1.12 on 2021-12-28 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.office'),
        ),
    ]
