# Generated by Django 3.1.12 on 2021-12-01 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
