# Generated by Django 3.1.12 on 2021-12-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.ImageField(blank=True, default=None, upload_to='static/images/barcodes'),
        ),
    ]
